trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.1.0

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py38]
    os: linux
    name_postfix: _go_1_14
    pre_test:
    - task: GoTool@0
      inputs:
        version: '1.14.8'
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy3, py36, py37, py38]
    os: linux
    name_postfix: _go_1_15
    pre_test:
    - task: GoTool@0
      inputs:
        version: '1.15.1'
